---
# root interfaces
switches:
  br-int:                   # internal switch
    ifname: br-int
    type: static
    address: 172.31.128.1
    netmask: 255.255.252.0
    ports:
     - ifname: eth1
  br-ex:                    # external switch
    ifname: br-ex
    type: static
    address: 0.0.0.0
    metmask: 255.255.255.0
namespaces:
  - name: node1
    interfaces:
    - ifname: einf0         # vNIC in namespace 
      type: static
      address: 0.0.0.0
      bridge:
        ifname: br0
        type: dhcp
  - name: node2
    interfaces:
    - ifname: einf0         # vNIC in namespace 
      type: static
      address: 0.0.0.0
      bridge:
        ifname: br0
        type: dhcp
  - name: node3
    interfaces:
    - ifname: einf0         # vNIC in namespace 
      type: static
      address: 0.0.0.0
      bridge:
        ifname: br0
        type: dhcp

